version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: jbuilder
    versions:
    - 2.11.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
